# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

minimal_mistakes_skin: "dark"

locale: "en-US"
title: Shadows of Intrigue
title_separator: "|"
name: &gmname "Adam Brown"
logo: "/assets/images/logos/sen.png"
email: adam.brown.x.ridley@gmail.com
description: A planned 5e story taking place in the Celestial city of Sen.
github_username:  RidleyB

domain: ridleyb.github.io
url: https://ridleyb.github.io
search: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false
footer_scripts: true

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
sass_dir: _sass
style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections_dir: content
collections:
   factions:
      output: true
      permalink: :collection/:title

   lore:
      output: true
      permalink: :collection/:title

   characters:
      output: true
      permalink: :collection/:title

   content:   
      output: true
      permalink: :collection/:title

   other:   
      output: true
      permalink: :collection/:title

include:
- .htaccess

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .sln
   - .vs

# custom global variables

families: "Blanchard, Del Vecchio, Montaigne, Reinhardt, Santini, Other"
path_logo: /assets/images/logos/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      comments: false
      share: false
      related: true
      disable_pagination: false
      disable_title: false
      excerpt_separator: <!--more-->
      related: false
      dead: false
      sidebar:
        nav: sidebar

  - scope:
      path: "content/_content"
    values:
      category: content
      disable_pagination: false
      disable_title: false
      excerpt_separator: <!--more-->
      header:
        overlay_image: /assets/images/sen-splash-2.jpg
        overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
        caption: ""
      sidebar:
        nav: sidebar

  - scope:
      path: "content/_characters"
    values:
      disable_pagination: false
      disable_title: true
      sidebar_excerpt: true
      sidebar_ext:
        before_nav: true
      category: characters
      toc: true
      toc_sticky: true
      sidebar:
        nav: sidebar
      char_data:
        - element_title: "Pronouns"
        - element_title: "Race"
        - element_title: "Age"
        - element_title: "Height"
        - element_title: "Hair"
        - element_title: "Skin"
        - element_title: "Eyes"
      related: false
      dead: false