# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

remote_theme: "mmistakes/minimal-mistakes@master"
theme_version: "4.25.1"
minimal_mistakes_skin: "dark"

locale: "en-US"
title: Shadows of Intrigue
title_separator: "|"
name: &gmname "Adam Brown"
logo: "/assets/images/sen-logo-256.png"
email: adam.brown.x.ridley@gmail.com
description: This is a description.
github_username:  RidleyB


domain: ridleyb.github.io
url: https://ridleyb.github.io

search: true

plugins:
  - jekyll-include-cache

author:
  name             : *gmname # *gmname is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/author.jpg"
  bio              : "Just a guy."
  location         : "The Celestial City"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      comments: true
      share: true
      related: true
