# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

minimal_mistakes_skin: "custom"

locale: "en-US"
url: "https://ridleyb.github.io"
baseurl: "/sen"
title: Ashes of the Fallen
title_separator: "|"
name: &gmname "Adam"
logo: "/assets/images/logo.png"
email: adam.brown.x.ridley@gmail.com
description: ""
github_username: "Ridley"

domain: ridleyb.github.io
url: https://ridleyb.github.io
search: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false
footer_scripts: true

timezone: America/New_York

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
sass_dir: _sass
style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

collections_dir: content
collections:
  factions:
    output: true
    permalink: :collection/:title

  lore:
    output: true
    permalink: :collection/:title

  character:
    output: true
    permalink: :collection/:title

  poi:
    output: true
    permalink: :collection/:title

  races:   
    output: true
    permalink: :collection/:title

  locations:   
    output: true
    permalink: :collection/:title

  devposts:
    output: true
    permalink: :collection/:title

  creatures:
    output: true
    permalink: :collection/:title

  sessions:
    output: true
    permalink: :collection/:title

  dev-sessions:
    output: true
    permalink: :collection/:title

  people:
    output: true
    permalink: :collection/:title


include:
- .htaccess

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .sln
   - .vs
   - _notincluded/
   - _devposts/dm/.git/

# custom global variables

path_logo: /assets/images/logos/

defaults:
  - scope:
      path: ""
    values:
      header:
        overlay_image: /assets/images/dawnspire-half.png
      layout: single
      disable_title: true
      disable_pagination: true
      excerpt_separator: <!--more-->
      sidebar:
        nav: sidebar

  - scope:
      path: "content/_character"
    values:
      category: character

  - scope:
      path: "content/_people"
    values:
      layout: single-character
      header: false
      sidebar_ext:
        before_nav: true
        image: true
      category: people
      sidebar:
        nav: story

  - scope:
      path: "content/_lore"
    values:
      category: lore

  - scope:
      path: "content/_sessions"
    values:
      category: sessions
      layout: single-character
      header: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: story

  - scope:
      path: "content/_locations"
    values:
      category: locations

  - scope:
      path: "content/_races"
    values:
      caption: ""
      category: races

  - scope:
      path: "content/_devposts"
    values:
      category: devposts
      header: false
      sidebar:
        nav: dev

  - scope:
      path: "content/_creatures"
    values:
      category: creatures
      layout: creature
      header: false
      sidebar:
        nav: dev

  - scope:
      path: "content/_dev-sessions"
    values:
      category: dev-sessions
      layout: session
      header: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: dev
